name 'platform_docker'
maintainer 'Jakub Błaszczyk'
maintainer_email 'jakub.blaszczyk@sap.com'
license 'all_rights'
description 'Installs/Configures chef-platform_docker'
long_description 'Installs/Configures chef-platform_docker'
version '0.1.0'
